/**
 * LuminaUI — Public entry point.
 *
 * Importing this module side-effect-registers every component with the
 * CustomElementRegistry. Tree-shakers will keep only the components you
 * actually reference if you import from the per-component paths instead.
 *
 * v0.3.0 — 100 components across 8 categories.
 */

import './components/lumina-alert';
import './components/lumina-autocomplete';
import './components/lumina-avatar-group';
import './components/lumina-avatar';
import './components/lumina-badge';
import './components/lumina-breadcrumbs';
import './components/lumina-breath-button';
import './components/lumina-breath-card';
import './components/lumina-button-group';
import './components/lumina-button';
import './components/lumina-card';
import './components/lumina-checkbox';
import './components/lumina-chip';
import './components/lumina-color-picker';
import './components/lumina-command-button';
import './components/lumina-command-palette';
import './components/lumina-confirmation-dialog';
import './components/lumina-container';
import './components/lumina-context-aware';
import './components/lumina-context-card';
import './components/lumina-context-input';
import './components/lumina-context-menu';
import './components/lumina-data-grid';
import './components/lumina-date-picker';
import './components/lumina-depth-controller';
import './components/lumina-dialog';
import './components/lumina-dimensional-card';
import './components/lumina-drawer-modal';
import './components/lumina-drawer';
import './components/lumina-echo-button';
import './components/lumina-echo-card';
import './components/lumina-echo-system';
import './components/lumina-fab';
import './components/lumina-file-upload';
import './components/lumina-floating-nav';
import './components/lumina-form';
import './components/lumina-form-field';
import './components/lumina-form-list';
import './components/lumina-fullscreen-overlay';
import './components/lumina-gesture-button';
import './components/lumina-glass-card';
import './components/lumina-glow-card';
import './components/lumina-grid';
import './components/lumina-masked-input';
import './components/lumina-holo-card';
import './components/lumina-hover-card';
import './components/lumina-icon-button';
import './components/lumina-image-zoom';
import './components/lumina-input';
import './components/lumina-lightbox';
import './components/lumina-liquid-card';
import './components/lumina-list';
import './components/lumina-loading';
import './components/lumina-magnetic-button';
import './components/lumina-mega-menu';
import './components/lumina-memory-card';
import './components/lumina-modal';
import './components/lumina-morph-button';
import './components/lumina-morph-card';
import './components/lumina-morph-lab';
import './components/lumina-multi-select';
import './components/lumina-navigation';
import './components/lumina-neural-button';
import './components/lumina-neural-card';
import './components/lumina-neural-input';
import './components/lumina-neural-loader';
import './components/lumina-notification-badge';
import './components/lumina-orbital-nav';
import './components/lumina-pagination';
import './components/lumina-parallax-card';
import './components/lumina-particle-card';
import './components/lumina-particle-system';
import './components/lumina-password-input';
import './components/lumina-popover';
import './components/lumina-portal-button';
import './components/lumina-progress-nav';
import './components/lumina-progress';
import './components/lumina-pulse-indicator';
import './components/lumina-radio-group';
import './components/lumina-range-slider';
import './components/lumina-reveal-card';
import './components/lumina-ripple-button';
import './components/lumina-search-input';
import './components/lumina-select';
import './components/lumina-sidebar';
import './components/lumina-signature-pad';
import './components/lumina-skeleton';
import './components/lumina-slider';
import './components/lumina-spinner';
import './components/lumina-split-button';
import './components/lumina-stack-card';
import './components/lumina-status-indicator';
import './components/lumina-step-indicator';
import './components/lumina-switch';
import './components/lumina-table';
import './components/lumina-tabs';
import './components/lumina-textarea';
import './components/lumina-time-picker';
import './components/lumina-timeline';
import './components/lumina-toast';
import './components/lumina-toggle-button';
import './components/lumina-toggle';
import './components/lumina-tooltip';
import './components/lumina-tree-view';
import './components/lumina-voice-input';
import './components/lumina-void-card';

export { LuminaElement } from './core/LuminaElement';
export type { LuminaElementAttributes } from './core/LuminaElement';
export { LuminaFormElement } from './core/LuminaFormElement';
export * from './core/types';
export * from './core/tokens';
export * from './core/utils';
export { ParticleField } from './core/ParticleField';
